// Code generated by MockGen. DO NOT EDIT.
// Source: go-tf-provisioner/internal/httpapi (interfaces: ProvisionService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_provision_service.go -package=mocks go-tf-provisioner/internal/httpapi ProvisionService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	provisioner "go-tf-provisioner/internal/provisioner"
	status "go-tf-provisioner/internal/status"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProvisionService is a mock of ProvisionService interface.
type MockProvisionService struct {
	ctrl     *gomock.Controller
	recorder *MockProvisionServiceMockRecorder
	isgomock struct{}
}

// MockProvisionServiceMockRecorder is the mock recorder for MockProvisionService.
type MockProvisionServiceMockRecorder struct {
	mock *MockProvisionService
}

// NewMockProvisionService creates a new mock instance.
func NewMockProvisionService(ctrl *gomock.Controller) *MockProvisionService {
	mock := &MockProvisionService{ctrl: ctrl}
	mock.recorder = &MockProvisionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvisionService) EXPECT() *MockProvisionServiceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockProvisionService) List(ctx context.Context, customerID, productCodeFilter string) ([]status.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, customerID, productCodeFilter)
	ret0, _ := ret[0].([]status.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProvisionServiceMockRecorder) List(ctx, customerID, productCodeFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProvisionService)(nil).List), ctx, customerID, productCodeFilter)
}

// Submit mocks base method.
func (m *MockProvisionService) Submit(ctx context.Context, req provisioner.ProvisionRequest) (provisioner.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, req)
	ret0, _ := ret[0].(provisioner.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockProvisionServiceMockRecorder) Submit(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockProvisionService)(nil).Submit), ctx, req)
}
